### ISSUE TITLE
Missing embeds

### ISSUE THREAD

**Issue by dhops** [lamypark/FlavorGraph#1]
Hi, I'd love to use the pre-trained embeddings, but the files seem to be missing and I can't run the code on my machine. Is it possible to fix those links? Thanks!

**Comment by baharefatemi** [comment]
I'm also having the same issue. The link to download the embedding is broken. Can you please share the pre-trained embedding?

**Comment by frankup69** [comment]
yes please reset the link

**Comment by lamypark** [comment]
Sorry all, I have recently updated the download link for FlavorGraph embedding.
